export const SETTINGS_DEFAULT_ITEM_COUNT_PER_PAGE = String(20);

export const  SETTINGS_DEFAULT_FONT_SIZE = 14;

export const  SETTINGS_DEFAULT_ANIMATIONS = false;

export const  SETTINGS_DEFAULT_INTERFACE_LANGUAGE = 'ru';

export const  SETTINGS_DEFAULT_CONTENT_LANGUAGE = 'ru';